Bookstore: styling
Gh-Reza/bookstore pull request #5
Opened 2023-07-21 18:00 UTC by Gh-Reza

## Changes:

- Added styles using CSS3
- Added styles using Bootstrap

2023-07-21 18:20 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @Gh-Reza 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️code is clean
✔️style almost identical
## Required Changes ♻️
- [ ] Please make these titles uppercased, remove the underlines, and color accordingly to match the zeplin design:

your design|zeplin
---|---
![image](https://github.com/Gh-Reza/bookstore/assets/91486791/89eeec14-55ff-48b2-914a-99507dbe1d03)|![image](https://github.com/Gh-Reza/bookstore/assets/91486791/8483ca55-f7bd-439d-94d8-c888870dc11a)

- [ ] Please use the same icon to match the zeplin design: 

your design|zeplin
---|---
![image](https://github.com/Gh-Reza/bookstore/assets/91486791/33167505-b229-49bf-af31-67fe7bf41db8)|![image](https://github.com/Gh-Reza/bookstore/assets/91486791/22117ef2-5394-48b0-82ef-10bd0a2ab284)


- [ ] Please use the same value for the colors and font weights rather than using Bootstrap 'primary' to match  the design:


your design|zeplin
---|---
![image](https://github.com/Gh-Reza/bookstore/assets/91486791/4d3b53ea-d077-4eeb-9272-93c7969677cf)|![image](https://github.com/Gh-Reza/bookstore/assets/91486791/6b3d1178-b9d7-4219-aba3-ce6710adb4cc)


- [ ] Please add the vertical short lines to match the zeplin design:

your design|zeplin
---|---
![image](https://github.com/Gh-Reza/bookstore/assets/91486791/b241bf3b-8f03-419e-b5be-9fe33a503301)|![image](https://github.com/Gh-Reza/bookstore/assets/91486791/3e3de968-6abe-43fe-a9ea-22b34c9eee55)

- [ ] Please use the same color and letter case for this title to match the designs

your design|zeplin
---|---
![image](https://github.com/Gh-Reza/bookstore/assets/91486791/8928ff80-cc00-43a9-9ec3-d72169023b6b)|![image](https://github.com/Gh-Reza/bookstore/assets/91486791/1038463f-f62a-491f-ab31-b4edfc589e7a)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 20:02 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @Gh-Reza :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Linters checks are passing.
✔️ Git flow is correct.
✔️ Readme is professional.

## Required Changes ♻️

***Please kindly check the comments/review below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 20:02 UTC, Tufahel commented on src/components/Book.jsx
>  );
- [ ] Kindly check the color of the fonts from the template and fix them according to the previous reviewer.
![image](https://github.com/Gh-Reza/bookstore/assets/60083437/a11b4dba-c0c0-421e-a29e-27455966b7b5)

2023-07-22 05:52 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Gh-Reza 

Your project is complete! Great job for naking the changes requested 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Works as expected
- great design
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-22 06:21 UTC, merged